#!/usr/bin/env python

from pulp.constants import (
    LpMinimize,
)
from pulp import (
    LpProblem,
    LpVariable,
    LpInteger,
    lpSum,
    allcombinations,
)

nmice = 1
nbottles = 2
npoisoned = 1
labels = range(2**nmice)

# Arbitrary large number to be used later
M = nbottles

# Initialize problem
prob = LpProblem("drunk_mice", LpMinimize)

# This is the answer, the allocation of bottles to each label:
allocs = LpVariable.dicts(
    "alloc",
    labels,
    0, nbottles,
    LpInteger,
)

# They must sum to nbottles:
prob += lpSum(allocs) == nbottles

# This is the number we are minimizing
worst_loss = LpVariable(
    "worst_loss",
    npoisoned,
    nbottles,
    LpInteger,
)

prob += worst_loss, "obj"

# This is the loss for each label
scenario_loss = LpVariable.dicts(
    "scenario_loss",
    labels,
    0, nbottles,
    LpInteger,
)

# The worst loss is worse than each scenario loss
for i in labels:
    prob += worst_loss >= scenario_loss[i]

# An scenario is generated by the overlapping of underlying
# labels. For each such set, if every underlying label has a non-zero
# allocation, then the allocations to all the labels must be added to
# the scenario loss

scenario2labels = {i : set() for i in labels}
scenario2label_sets = {i : set() for i in labels}
for label_set in allcombinations(labels, npoisoned):
    scenario = 0
    for label in label_set:
        scenario |= label
    scenario2label_sets[scenario].add(label_set)
    for label in label_set:
        scenario2labels[scenario].add(label)

alloc_nonzero = LpVariable.dicts(
    "alloc_nonzero",
    labels, 0, 1,
    LpInteger,
)
for i in labels:
    alloc0 = allocs[i]
    nonzero0 = alloc_nonzero[i]
    prob += alloc0 <= nonzero0 * M


for scenario in labels:
    scenario_labels = [(scenario, i) for i in scenario2labels[scenario]]
    scenario_label_sets = [(scenario, ls) for ls in scenario2label_sets[scenario]]
    label_nonzero = LpVariable.dicts(
        "label_nonzero",
        scenario_labels,
        0, nbottles, LpInteger,
    )
    label_sets = LpVariable.dicts(
        "label_set_active",
        scenario_label_sets,
        0, 1, LpInteger,
    )

    for label_set0 in scenario_label_sets:
        label_set_var = label_sets[label_set0]
        prob += lpSum([alloc_nonzero[i] for i in label_set0[1]]) - len(label_set0[1]) >= - label_set_var * M
        for label0 in label_set0[1]:
            prob += label_nonzero[(scenario, label0)] >= label_set_var

    loss = scenario_loss[scenario]
    label_loss = LpVariable.dicts(
        "label_loss",
        scenario_labels,
        0, nbottles, LpInteger,
    )
    prob += lpSum(label_loss) == loss

    for label0 in scenario_labels:
        prob += label_loss[label0] >= allocs[label0[1]] - (1 - label_nonzero[label0]) * M

prob.writeLP("drunk_mice.lp")
prob.solve()
